# The value of AppId uniquely identifies this application.
# Do not use the same AppId value in installers for other applications.
app_id: 3928571b-18e9-5163-8e72-5b80626a8ca5
publisher: Kushal
publisher_url: 
display_name: MediaLabs
create_desktop_icon: true
# See: https://jrsoftware.org/ishelp/index.php?topic=setup_defaultdirname
# install_dir_name: "D:\\HELLO-WORLD"
# This path is relative to the root directory of your project; The format of icon file must be ico, can not be png or others
# setup_icon_file: windows\runner\resources\app_icon.ico
locales:
  - en