name: example
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.0

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  media:
    path: ../
  file_picker: ^10.3.7
  image_picker: ^1.2.1
  path: ^1.9.1
  path_provider: ^2.1.5
  media_kit: ^1.2.6
  media_kit_video: ^2.0.1
  media_kit_libs_video: ^1.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  inno_bundle: ^0.11.2

flutter:
  uses-material-design: true


inno_bundle:
  id: 3928571b-18e9-5163-8e72-5b80626a8ca5
  publisher: Kushal
  name: Media Labs