name: media_workspace
description: A media processing library.
version: 0.0.1

environment:
  sdk: '>=3.10.0 <4.0.0'

workspace:
  - media
  - example

dependencies:
  freezed_annotation: ^2.4.4
  path: ^1.9.1
  http: ^1.2.0
  code_assets: ^1.0.0
  logging: ^1.3.0
  hooks: ^1.0.0
  native_toolchain_rust: ^1.0.3
  native_assets_cli: ^0.18.0
  yaml: ^3.1.3
  toml: ^0.18.0

inno_bundle:
  id: 64ee1df0-faca-11f0-acd6-db79663d1ab8
  publisher: kusha