name: media
description: A media based library Dart.
version: 0.0.1+1
homepage: https://katim.com
publish_to: 'https://artifactory.katim.com/artifactory/api/pub/pub-dev-virtual/' 

environment:
  sdk: "^3.10.0"

resolution: workspace

dev_dependencies:
  build_runner: ^2.4.7
  ffigen: ^20.1.0
  freezed: ^2.4.7
  json_serializable: ^6.7.1
  test: ^1.16.0

dependencies:
  code_assets: ^1.0.0
  ffi: ^2.1.4
  flutter_rust_bridge: ^2.11.1
  freezed_annotation:
  logging: ^1.3.0
  path: ^1.9.1
  hooks: ^1.0.0
  native_toolchain_rust: ^1.0.3
  native_assets_cli: ^0.18.0

