display_name: Media Labs
package_name: medialabs

maintainer:
  name: Kushal Mahapatro
  email: kushalmahapatro@gmail.com

priority: optional

section: x11

installed_size: 15700

dependencies:

essential: false

# icon: 

postuninstall_scripts:
  - echo "Sorry to see you go."

keywords:
  - Video Compression
  - Video Thumbnail Generation

generic_name: Media Labs

categories:
  - Development
  - Utility

startup_notify: true